import type { CalendarTheme } from "./types";

export const defaultTheme: CalendarTheme = {
  "--ce-bg": "#ffffff",
  "--ce-bg-secondary": "#f8f9fa",
  "--ce-text": "#1a1a2e",
  "--ce-text-muted": "#6b7280",
  "--ce-primary": "#6366f1",
  "--ce-primary-hover": "#4f46e5",
  "--ce-primary-text": "#ffffff",
  "--ce-border": "#e5e7eb",
  "--ce-border-hover": "#d1d5db",
  "--ce-slot-available": "#ecfdf5",
  "--ce-slot-hover": "#d1fae5",
  "--ce-slot-selected": "#6366f1",
  "--ce-event-bg": "#eef2ff",
  "--ce-event-text": "#3730a3",
  "--ce-event-recurring-bg": "#fef3c7",
  "--ce-booking-bg": "#dbeafe",
  "--ce-today-bg": "#eff6ff",
  "--ce-radius": "8px",
  "--ce-radius-sm": "4px",
  "--ce-radius-lg": "12px",
  "--ce-font-family": "system-ui, -apple-system, sans-serif",
  "--ce-font-size": "14px",
  "--ce-font-size-sm": "12px",
  "--ce-font-size-lg": "16px",
  "--ce-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
  "--ce-transition": "150ms ease",
};
